/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17337 2009-01-01 14:28:29Z magfr $
 */
#ifndef MEDIA_H
#define MEDIA_H

#define IMAGE_SOURCE_LEN    256	
#define MAX_URL_LEN         512
#define PLAYLIST_LEN        128
#define MAX_FILENAME_LEN	255
#define MAX_PATH_LEN		48

#define PT_RAM		0
#define PT_FLASH	1
#define PT_HD		2
#define PT_USB		3

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    char image1SourceAddress[IMAGE_SOURCE_LEN + 1];
    char image2SourceAddress[IMAGE_SOURCE_LEN + 1];
    char image3SourceAddress[IMAGE_SOURCE_LEN + 1];
    int fileTypeIndex;
    char playlistDevice;
    int playlistIndex;
} MediaConfig;

typedef enum {
    FileType_Unknown,
    FileType_Video,
    FileType_Audio,
    FileType_Picture,
    FileType_Playlist,
    FileType_Html,
    FileType_VideoProfile,
    FileType_HTTP,
    FileType_UDP,
    FileType_RTP,
    FileType_Invalid
} FileType;

typedef struct {
    char url[MAX_URL_LEN + 1];
    char filename[PLAYLIST_LEN + 1];
    FileType type;
} DownloadCfg;

void init_media(MediaConfig *setting);
const char *FileTypeIndexCurrent();
const char *FileTypeString(FileType type);

#ifdef __cplusplus
}
#endif
Netsnmp_Node_Handler handle_image1SourceAddress;
Netsnmp_Node_Handler handle_image2SourceAddress;
Netsnmp_Node_Handler handle_image3SourceAddress;
Netsnmp_Node_Handler handle_activeMedia;
Netsnmp_Node_Handler handle_fileTypeIndex;
Netsnmp_Node_Handler handle_renameMediaFile;
Netsnmp_Node_Handler handle_deleteMediaFile;
Netsnmp_Node_Handler handle_freeSpace;
Netsnmp_Node_Handler handle_storeVideoFile;
Netsnmp_Node_Handler handle_storeAudioFile;
Netsnmp_Node_Handler handle_storeImageFile;
Netsnmp_Node_Handler handle_targetPlaylistFile;
Netsnmp_Node_Handler handle_storePlaylistFile;
Netsnmp_Node_Handler handle_transferControl;
Netsnmp_Node_Handler handle_storeBrowserFile;
Netsnmp_Node_Handler handle_ftpPut;

#endif                          /* MEDIA_H */
