/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17337 2009-01-01 14:28:29Z magfr $
 */
#ifndef MONITOR_H
#define MONITOR_H

#define MODEL_LEN           32
#define SERIAL_DATA_LEN     28
#define INSTALL_PLACE_LEN   32
#define SERIAL_PARM_LEN     20
#define MAX_SERIAL_LEN		256

/* Monitor Type */
#define MT_SONY         1
#define MT_LG           2
#define MT_NEC          3
#define MT_PANASONIC    4
#define MT_PIONEER      5
#define MT_SAMSUNG      6
#define MT_UNDEFINED    7
#define MT_PASSTHRU     8

typedef struct {
    int type;
    char model[MODEL_LEN + 1];
	char serial_data[SERIAL_DATA_LEN + 1];
	int serial_data_len;
    unsigned char display_power;
    unsigned char display_input;
    int display_volume;
    int display_fp;
    int monitor_mute;
//    int resolution;
    int interlace;
    int interlacing_value;
    char install_place[INSTALL_PLACE_LEN + 1];
    int protocol;
    char serial_parameters[SERIAL_PARM_LEN + 1];
    int passthru_buffer_enable;
    int passthru_buffer_size;
    int video3d_config;
} MonitorConfig;

#include <MediaPlayerAppDef.h>

#ifdef __cplusplus
extern "C" {
#endif

void init_monitor(MonitorConfig *setting);

#ifdef __cplusplus
}
#endif

Netsnmp_Node_Handler handle_monitorType;
Netsnmp_Node_Handler handle_monitorModel;
Netsnmp_Node_Handler handle_serialControlData;
Netsnmp_Node_Handler handle_monitorPower;
Netsnmp_Node_Handler handle_monitorInput;
Netsnmp_Node_Handler handle_monitorVolume;
Netsnmp_Node_Handler handle_monitorFrontPanel;
Netsnmp_Node_Handler handle_monitorMute;
Netsnmp_Node_Handler handle_videoDisplayResolution;
Netsnmp_Node_Handler handle_videoInterlacing;
Netsnmp_Node_Handler handle_videoInterlacingValue;
Netsnmp_Node_Handler handle_monitorLocation;
Netsnmp_Node_Handler handle_monitorProtocol;
Netsnmp_Node_Handler handle_serialParameters;
Netsnmp_Node_Handler handle_passthruBufferEnable;
Netsnmp_Node_Handler handle_passthruBufferSize;
Netsnmp_Node_Handler handle_3DConfiguration;
Netsnmp_Node_Handler handle_DisplayOutputMode;

#endif                          /* MONITOR_H */
