/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17337 2009-01-01 14:28:29Z magfr $
 */
#ifndef NETWORK_H
#define NETWORK_H

#define SMB_USER_LEN        32
#define SMB_PASSWORD_LEN    32
#define SMB_SHARE_LEN       64	

#define WIRELESS_CHAN_MAX   13
#define WIRELESS_SEC_MAX    3
#include <iwlib.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    struct in_addr ip_add;
    struct in_addr subnet;
    struct in_addr gateway;
    struct in_addr pri_dns;
    struct in_addr sec_dns;
    unsigned char dhcp_setting;
    unsigned char devName[48];
    int control;
} NetworkInfo;

typedef struct {
    char ssid[IW_ESSID_MAX_SIZE + 1];
    char key[IW_ENCODING_TOKEN_MAX];
    int channel;
    int security;
    int iWepKeyIndex;
    int type;
} WifiApInfo;

typedef struct {
    char user[SMB_USER_LEN + 1];
    char passwd[SMB_PASSWORD_LEN + 1];
    char sharename[SMB_SHARE_LEN + 1];
    int mountInitiate;
} SMBInfo;

typedef struct {
    unsigned char domainName[48];
    NetworkInfo wired;
    NetworkInfo wifi;
    WifiApInfo wifiAp;
    SMBInfo smb;
    int bInitialized;
    int bInitWifiCfg;
} NetworkConfig;

typedef enum {
    ACommit_TYPE_immediatelySaveWired,
    ACommit_TYPE_nextBootWired,
    ACommit_TYPE_immediatelyNoSaveWired,
    ACommit_TYPE_immediatelySaveWireless,
    ACommit_TYPE_nextBootWireless,
    ACommit_TYPE_immediatelyNoSaveWireless,
    ACommit_TYPE_invalid
} NetworkConfigCommit_TYPE, *P_NetworkConfigCommit_TYPE;

/*
 * function declarations 
 */
void init_network();

#ifdef __cplusplus
}
#endif

Netsnmp_Node_Handler handle_tnetIPAddress;
Netsnmp_Node_Handler handle_tnetSubnetAddress;
Netsnmp_Node_Handler handle_tnetGatewayAddress;
Netsnmp_Node_Handler handle_tnetPriDNS;
Netsnmp_Node_Handler handle_tnetSecDNS;
Netsnmp_Node_Handler handle_tnetDHCPEnable;
Netsnmp_Node_Handler handle_netCommit;
Netsnmp_Node_Handler handle_macAddress;
Netsnmp_Node_Handler handle_smbUser;
Netsnmp_Node_Handler handle_smbPassword;
Netsnmp_Node_Handler handle_smbMountShareName;
Netsnmp_Node_Handler handle_smbMountInitiate;
Netsnmp_Node_Handler handle_domainName;
Netsnmp_Node_Handler handle_tnetWirelessIPAddress;
Netsnmp_Node_Handler handle_tnetWirelessSubnetAddress;
Netsnmp_Node_Handler handle_tnetWirelessGatewayAddress;
Netsnmp_Node_Handler handle_tnetWirelessPriDNS;
Netsnmp_Node_Handler handle_tnetWirelessSecDNS;
Netsnmp_Node_Handler handle_tnetWirelessDHCPEnable;
Netsnmp_Node_Handler handle_tnetWirelessSSID;
Netsnmp_Node_Handler handle_tnetWirelessConnectionType;
Netsnmp_Node_Handler handle_tnetWirelessKey;
Netsnmp_Node_Handler handle_tnetWirelessChannel;
Netsnmp_Node_Handler handle_tnetWirelessChannelStrength;
Netsnmp_Node_Handler handle_tnetWirelessDomainName;
Netsnmp_Node_Handler handle_tnetWiredControl;
Netsnmp_Node_Handler handle_tnetWirelessControl;
Netsnmp_Node_Handler handle_tnetWirelessSecurity;
Netsnmp_Node_Handler handle_tnetWirelessWepKeyIndex;
#endif                          /* NETWORK_H */
