/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17337 2009-01-01 14:28:29Z magfr $
 */
#ifndef SYSTEM_H
#define SYSTEM_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
} SystemConfig;

/*
 * function declarations 
 */
void init_system(void);

#ifdef __cplusplus
}
#endif

Netsnmp_Node_Handler handle_cardCurrentStatus;
Netsnmp_Node_Handler handle_currentClockTicks;
Netsnmp_Node_Handler handle_mediaKey;
Netsnmp_Node_Handler handle_formatMedia;
Netsnmp_Node_Handler handle_scanMedia;
Netsnmp_Node_Handler handle_mediaStatus;
Netsnmp_Node_Handler handle_rebootSystem;
Netsnmp_Node_Handler handle_firmwareUpgradeAddress;
Netsnmp_Node_Handler handle_autoAnnounce;
Netsnmp_Node_Handler handle_communicationProtocol;
Netsnmp_Node_Handler handle_configSave;
Netsnmp_Node_Handler handle_configSaveOption;
Netsnmp_Node_Handler handle_tnetVersion;
Netsnmp_Node_Handler handle_selfTest;
Netsnmp_Node_Handler handle_priTimeServer;
Netsnmp_Node_Handler handle_secTimeServer;
Netsnmp_Node_Handler handle_timeZone;
Netsnmp_Node_Handler handle_pushConfig;
Netsnmp_Node_Handler handle_pullConfig;
Netsnmp_Node_Handler handle_restorePreviousConfiguration;
Netsnmp_Node_Handler handle_transferLog;
Netsnmp_Node_Handler handle_softwareUpgradeAddress;
Netsnmp_Node_Handler handle_userOSDAddress;
Netsnmp_Node_Handler handle_deviceKey;
Netsnmp_Node_Handler handle_enabledFeatures;
Netsnmp_Node_Handler handle_maintainLog;
Netsnmp_Node_Handler handle_irControl;
Netsnmp_Node_Handler handle_trapEnable;
Netsnmp_Node_Handler handle_trapReceiverAddress;
Netsnmp_Node_Handler handle_webAdminPassword;
Netsnmp_Node_Handler handle_snmpV3Only;
Netsnmp_Node_Handler handle_snmpCommunity;
Netsnmp_Node_Handler handle_multipleUpgradeAddress;
Netsnmp_Node_Handler handle_gpioInterruptSource;
Netsnmp_Node_Handler handle_configDateTime;
Netsnmp_Node_Handler handle_loggingEnable;
Netsnmp_Node_Handler handle_xappVersion;
Netsnmp_Node_Handler handle_systemUpgradeAddress;
Netsnmp_Node_Handler handle_autoReboot;
Netsnmp_Node_Handler handle_autoRebootInterval;
Netsnmp_Node_Handler handle_audioOutputMode;
Netsnmp_Node_Handler handle_dispOsdResolutionId; 
Netsnmp_Node_Handler handle_cpuSerialNo;
Netsnmp_Node_Handler handle_IrOut; 
Netsnmp_Node_Handler handle_touchScreenCalibrate;
Netsnmp_Node_Handler handle_HdmiCecCtrl;
Netsnmp_Node_Handler handle_IrLevelOut;
Netsnmp_Node_Handler handle_enableAudio6Ch;
//add by bert 2016/08/27
Netsnmp_Node_Handler handle_hardwareCapability;


#endif                          /* SYSTEM_H */
