#ifndef	_MEDIA_DATA_TYPE_H_
#define	_MEDIA_DATA_TYPE_H_

typedef enum
{
	MDP_TYPE_UNKNOWN,
	MDP_TYPE_ASF_HEADER,
	MDP_TYPE_ASF_DATA,
}MEDIA_DATA_PACKET_TYPE, *P_MEDIA_DATA_PACKET_TYPE;

#endif	//_MEDIA_DATA_TYPE_H_

