#ifndef	_PARCEL_PROTOCOL_H_
#define	_PARCEL_PROTOCOL_H_

#define	PARCEL_MSG_TYPE_METHOD_CALL			1
#define	PARCEL_MSG_TYPE_METHOD_REPLY		2
#define	PARCEL_MSG_TYPE_METHOD_SIGNAL		3

#endif	//_PARCEL_PROTOCOL_H_
