/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $
 *
 * $Id:$
 *
 * @file channelTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef CHANNELTABLE_DATA_GET_H
#define CHANNELTABLE_DATA_GET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * GET function declarations
     */

    /*
     *********************************************************************
     * GET Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table channelTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * CE-SNMP-MIB::channelTable is subid 7 of tuner.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.38010.3.8.7, length: 10
     */
    /*
     * indexes
     */
    int             channelIndex_get(channelTable_rowreq_ctx * rowreq_ctx,
                                      long *channelIndex_val_ptr);
    int             channelNumber_get(channelTable_rowreq_ctx * rowreq_ctx,
                                      long *channelNumber_val_ptr);
    int             subChannelCount_get(channelTable_rowreq_ctx *
                                        rowreq_ctx,
                                        long *subChannelCount_val_ptr);
    int             programID_get(channelTable_rowreq_ctx * rowreq_ctx,
                                  char **programID_val_ptr_ptr,
                                  size_t *programID_val_ptr_len_ptr);


    int             channelTable_indexes_set_tbl_idx(channelTable_mib_index
                                                     * tbl_idx,
                                                     long
                                                     channelIndex_val);
    int             channelTable_indexes_set(channelTable_rowreq_ctx *
                                             rowreq_ctx,
                                             long channelIndex_val);




#ifdef __cplusplus
}
#endif
#endif                          /* CHANNELTABLE_DATA_GET_H */
/** @} */
