/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $
 *
 * $Id:$
 */
#ifndef CHANNELTABLE_DATA_ACCESS_H
#define CHANNELTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     *********************************************************************
     * function declarations
     */

    /*
     *********************************************************************
     * Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table channelTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * CE-SNMP-MIB::channelTable is subid 7 of tuner.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.38010.3.8.7, length: 10
     */
#define CHANNELTABLE_CACHE_TIMEOUT   5


    int             channelTable_init_data(channelTable_registration *
                                           channelTable_reg);


    void            channelTable_container_init(netsnmp_container ** container_ptr_ptr, netsnmp_cache *cache);
    void            channelTable_container_shutdown(netsnmp_container *
                                                    container_ptr);

    int             channelTable_container_load(netsnmp_container *
                                                container);
    void            channelTable_container_free(netsnmp_container *
                                                container);

    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    /*
     *********************************************************************
     * Since we have no idea how you really access your data, we'll go with
     * a worst case example: a flat text file.
     */
#define MAX_LINE_SIZE 256
    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/
    int             channelTable_row_prep(channelTable_rowreq_ctx *
                                          rowreq_ctx);



#ifdef __cplusplus
}
#endif
#endif                          /* CHANNELTABLE_DATA_ACCESS_H */
