/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c 17548 2009-04-23 16:35:18Z hardaker $
 *
 * $Id:$
 */
#ifndef CHANNELTABLE_OIDS_H
#define CHANNELTABLE_OIDS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     * column number definitions for table channelTable 
     */
#define CHANNELTABLE_OID              1,3,6,1,4,1,38010,3,8,7


#define COLUMN_CHANNELINDEX         1

#define COLUMN_CHANNELNUMBER         2

#define COLUMN_SUBCHANNELCOUNT         3

#define COLUMN_PROGRAMID         4


#define CHANNELTABLE_MIN_COL   COLUMN_CHANNELINDEX
#define CHANNELTABLE_MAX_COL   COLUMN_PROGRAMID



#ifdef __cplusplus
}
#endif
#endif                          /* CHANNELTABLE_OIDS_H */
