/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 17337 $ of $ 
 *
 * $Id:$
 */
/** \page MFD helper for channelTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/*
 * include our parent header 
 */
#include "channelTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "channelTable_interface.h"

const oid       channelTable_oid[] = { CHANNELTABLE_OID };

const int       channelTable_oid_size = OID_LENGTH(channelTable_oid);

channelTable_registration channelTable_user_context;

void            initialize_table_channelTable(void);
void            shutdown_table_channelTable(void);


/**
 * Initializes the channelTable module
 */
void
init_channelTable(void)
{
    DEBUGMSGTL(("verbose:channelTable:init_channelTable", "called\n"));

    /*
     * TODO:300:o: Perform channelTable one-time module initialization.
     */

    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("channelTable"))
        initialize_table_channelTable();

}                               /* init_channelTable */

/**
 * Shut-down the channelTable module (agent is exiting)
 */
void
shutdown_channelTable(void)
{
    if (should_init("channelTable"))
        shutdown_table_channelTable();

}

/**
 * Initialize the table channelTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_channelTable(void)
{
    channelTable_registration *user_context;
    u_long          flags;

    DEBUGMSGTL(("verbose:channelTable:initialize_table_channelTable",
                "called\n"));

    /*
     * TODO:301:o: Perform channelTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize channelTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("channelTable", NULL, NULL);

    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;

    /*
     * call interface initialization code
     */
    _channelTable_initialize_interface(user_context, flags);
}                               /* initialize_table_channelTable */

/**
 * Shutdown the table channelTable 
 */
void
shutdown_table_channelTable(void)
{
    /*
     * call interface shutdown code
     */
    _channelTable_shutdown_interface(&channelTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
channelTable_rowreq_ctx_init(channelTable_rowreq_ctx * rowreq_ctx,
                             void *user_init_ctx)
{
    UNUSED(user_init_ctx);
    DEBUGMSGTL(("verbose:channelTable:channelTable_rowreq_ctx_init",
                "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:210:o: |-> Perform extra channelTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
}                               /* channelTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void
channelTable_rowreq_ctx_cleanup(channelTable_rowreq_ctx * rowreq_ctx)
{
    DEBUGMSGTL(("verbose:channelTable:channelTable_rowreq_ctx_cleanup",
                "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:211:o: |-> Perform extra channelTable rowreq cleanup.
     */
}                               /* channelTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
channelTable_pre_request(channelTable_registration * user_context)
{
    UNUSED(user_context);
    DEBUGMSGTL(("verbose:channelTable:channelTable_pre_request",
                "called\n"));

    /*
     * TODO:510:o: Perform channelTable pre-request actions.
     */

    return MFD_SUCCESS;
}                               /* channelTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
channelTable_post_request(channelTable_registration * user_context, int rc)
{
    UNUSED(user_context);
    UNUSED(rc);
    DEBUGMSGTL(("verbose:channelTable:channelTable_post_request",
                "called\n"));

    /*
     * TODO:511:o: Perform channelTable post-request actions.
     */

    return MFD_SUCCESS;
}                               /* channelTable_post_request */


/** @{ */
