/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 16927 $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef CHANNELTABLE_INTERFACE_H
#define CHANNELTABLE_INTERFACE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include "channelTable.h"


    /*
     ********************************************************************
     * Table declarations
     */

    /*
     * PUBLIC interface initialization routine 
     */
    void           
        _channelTable_initialize_interface(channelTable_registration *
                                           user_ctx, u_long flags);
    void           
        _channelTable_shutdown_interface(channelTable_registration *
                                         user_ctx);

    channelTable_registration *channelTable_registration_get(void);

    channelTable_registration
        *channelTable_registration_set(channelTable_registration * newreg);

    netsnmp_container *channelTable_container_get(void);
    int             channelTable_container_size(void);

    channelTable_rowreq_ctx *channelTable_allocate_rowreq_ctx(void *);
    void            channelTable_release_rowreq_ctx(channelTable_rowreq_ctx
                                                    * rowreq_ctx);

    int             channelTable_index_to_oid(netsnmp_index * oid_idx,
                                              channelTable_mib_index *
                                              mib_idx);
    int             channelTable_index_from_oid(netsnmp_index * oid_idx,
                                                channelTable_mib_index *
                                                mib_idx);

    /*
     * access to certain internals. use with caution!
     */
    void            channelTable_valid_columns_set(netsnmp_column_info
                                                   *vc);


#ifdef __cplusplus
}
#endif
#endif                          /* CHANNELTABLE_INTERFACE_H */
/** @} */
