/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 16927 $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef FILELISTINGTABLE_INTERFACE_H
#define FILELISTINGTABLE_INTERFACE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include "fileListingTable.h"


    /*
     ********************************************************************
     * Table declarations
     */

    /*
     * PUBLIC interface initialization routine 
     */
    void           
        _fileListingTable_initialize_interface
        (fileListingTable_registration * user_ctx, u_long flags);
    void           
        _fileListingTable_shutdown_interface(fileListingTable_registration
                                             * user_ctx);

    fileListingTable_registration *fileListingTable_registration_get(void);

    fileListingTable_registration
        *fileListingTable_registration_set(fileListingTable_registration *
                                           newreg);

    netsnmp_container *fileListingTable_container_get(void);
    int             fileListingTable_container_size(void);

    fileListingTable_rowreq_ctx *fileListingTable_allocate_rowreq_ctx(void
                                                                      *);
    void           
        fileListingTable_release_rowreq_ctx(fileListingTable_rowreq_ctx *
                                            rowreq_ctx);

    int             fileListingTable_index_to_oid(netsnmp_index * oid_idx,
                                                  fileListingTable_mib_index
                                                  * mib_idx);
    int             fileListingTable_index_from_oid(netsnmp_index *
                                                    oid_idx,
                                                    fileListingTable_mib_index
                                                    * mib_idx);

    /*
     * access to certain internals. use with caution!
     */
    void            fileListingTable_valid_columns_set(netsnmp_column_info
                                                       *vc);


#ifdef __cplusplus
}
#endif
#endif                          /* FILELISTINGTABLE_INTERFACE_H */
/** @} */
