/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c 17548 2009-04-23 16:35:18Z hardaker $
 *
 * $Id:$
 */
#ifndef FILELISTINGTABLE_OIDS_H
#define FILELISTINGTABLE_OIDS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     * column number definitions for table fileListingTable 
     */
#define FILELISTINGTABLE_OID              1,3,6,1,4,1,38010,3,4,6


#define COLUMN_FILEINDEX         1

#define COLUMN_FILENAME         2

#define COLUMN_FILESIZE         3


#define FILELISTINGTABLE_MIN_COL   COLUMN_FILENAME
#define FILELISTINGTABLE_MAX_COL   COLUMN_FILESIZE



#ifdef __cplusplus
}
#endif
#endif                          /* FILELISTINGTABLE_OIDS_H */
