/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 17337 $ of $
 *
 * $Id:$
 */
#ifndef FILELISTINGTABLE_H
#define FILELISTINGTABLE_H

#ifdef __cplusplus
extern          "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>
#include "subagent.h"

    /*
     * other required module components 
     */
    /* *INDENT-OFF*  */
config_add_mib(CE-SNMP-MIB)
config_require(CE-SNMP-MIB/fileListingTable/fileListingTable_interface)
config_require(CE-SNMP-MIB/fileListingTable/fileListingTable_data_access)
config_require(CE-SNMP-MIB/fileListingTable/fileListingTable_data_get)
config_require(CE-SNMP-MIB/fileListingTable/fileListingTable_data_set)
    /* *INDENT-ON*  */

    /*
     * OID and column number definitions for fileListingTable 
     */
#include "fileListingTable_oids.h"

    /*
     * enum definions 
     */
#include "fileListingTable_enums.h"

    /*
     *********************************************************************
     * function declarations
     */
    void            init_fileListingTable(void);
    void            shutdown_fileListingTable(void);

    /*
     *********************************************************************
     * Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table fileListingTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * CE-SNMP-MIB::fileListingTable is subid 6 of media.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.38010.3.4.6, length: 10
     */
    /*
     *********************************************************************
     * When you register your mib, you get to provide a generic
     * pointer that will be passed back to you for most of the
     * functions calls.
     *
     * TODO:100:r: Review all context structures
     */
    /*
     * TODO:101:o: |-> Review fileListingTable registration context.
     */
    typedef netsnmp_data_list fileListingTable_registration;

/**********************************************************************/
    /*
     * TODO:110:r: |-> Review fileListingTable data context structure.
     * This structure is used to represent the data for fileListingTable.
     */
    /*
     * This structure contains storage for all the columns defined in the
     * fileListingTable.
     */
    typedef struct fileListingTable_data_s {

        /*
         * fileName(2)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/h
         */
        char            fileName[256];
        size_t          fileName_len;   /* # of char elements, not bytes */

        /*
         * fileSize(3)/COUNTER64/ASN_COUNTER64/U64(U64)//l/A/w/e/r/d/h
         */
        U64             fileSize;

    } fileListingTable_data;


    /*
     * TODO:120:r: |-> Review fileListingTable mib index.
     * This structure is used to represent the index for fileListingTable.
     */
    typedef struct fileListingTable_mib_index_s {

        /*
         * fileIndex(1)/INTEGER/ASN_INTEGER/long(long)//l/a/w/e/R/d/h
         */
        long            fileIndex;


    } fileListingTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review fileListingTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
     */
#define MAX_fileListingTable_IDX_LEN     1


    /*
     *********************************************************************
     * TODO:130:o: |-> Review fileListingTable Row request (rowreq) context.
     * When your functions are called, you will be passed a
     * fileListingTable_rowreq_ctx pointer.
     */
    typedef struct fileListingTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
        netsnmp_index   oid_idx;
        oid             oid_tmp[MAX_fileListingTable_IDX_LEN];

        fileListingTable_mib_index tbl_idx;

        fileListingTable_data data;

        /*
         * flags per row. Currently, the first (lower) 8 bits are reserved
         * for the user. See mfd.h for other flags.
         */
        u_int           rowreq_flags;

        /*
         * TODO:131:o: |   |-> Add useful data to fileListingTable rowreq context.
         */

        /*
         * storage for future expansion
         */
        netsnmp_data_list *fileListingTable_data_list;

    } fileListingTable_rowreq_ctx;

    typedef struct fileListingTable_ref_rowreq_ctx_s {
        fileListingTable_rowreq_ctx *rowreq_ctx;
    } fileListingTable_ref_rowreq_ctx;

    /*
     *********************************************************************
     * function prototypes
     */
    int            
        fileListingTable_pre_request(fileListingTable_registration *
                                     user_context);
    int            
        fileListingTable_post_request(fileListingTable_registration *
                                      user_context, int rc);

    int            
        fileListingTable_rowreq_ctx_init(fileListingTable_rowreq_ctx *
                                         rowreq_ctx, void *user_init_ctx);
    void           
        fileListingTable_rowreq_ctx_cleanup(fileListingTable_rowreq_ctx *
                                            rowreq_ctx);


    fileListingTable_rowreq_ctx
        *fileListingTable_row_find_by_mib_index(fileListingTable_mib_index
                                                * mib_idx);

    extern const oid fileListingTable_oid[];
    extern const int fileListingTable_oid_size;


#include "fileListingTable_interface.h"
#include "fileListingTable_data_access.h"
#include "fileListingTable_data_get.h"
#include "fileListingTable_data_set.h"

    /*
     * DUMMY markers, ignore
     *
     * TODO:099:x: *************************************************************
     * TODO:199:x: *************************************************************
     * TODO:299:x: *************************************************************
     * TODO:399:x: *************************************************************
     * TODO:499:x: *************************************************************
     */

#ifdef __cplusplus
}
#endif
#endif                          /* FILELISTINGTABLE_H */
/** @} */
