/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $
 *
 * $Id:$
 *
 * @file fileListingTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef FILELISTINGTABLE_DATA_GET_H
#define FILELISTINGTABLE_DATA_GET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * GET function declarations
     */

    /*
     *********************************************************************
     * GET Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table fileListingTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * CE-SNMP-MIB::fileListingTable is subid 6 of media.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.38010.3.4.6, length: 10
     */
    /*
     * indexes
     */

    int             fileName_get(fileListingTable_rowreq_ctx * rowreq_ctx,
                                 char **fileName_val_ptr_ptr,
                                 size_t *fileName_val_ptr_len_ptr);
    int             fileSize_get(fileListingTable_rowreq_ctx * rowreq_ctx,
                                 U64 * fileSize_val_ptr);


    int            
        fileListingTable_indexes_set_tbl_idx(fileListingTable_mib_index *
                                             tbl_idx, long fileIndex_val);
    int            
        fileListingTable_indexes_set(fileListingTable_rowreq_ctx *
                                     rowreq_ctx, long fileIndex_val);




#ifdef __cplusplus
}
#endif
#endif                          /* FILELISTINGTABLE_DATA_GET_H */
/** @} */
