/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 17337 $ of $ 
 *
 * $Id:$
 */
/** \page MFD helper for fileListingTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/*
 * include our parent header 
 */
#include "fileListingTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "fileListingTable_interface.h"

const oid       fileListingTable_oid[] = { FILELISTINGTABLE_OID };

const int       fileListingTable_oid_size =
OID_LENGTH(fileListingTable_oid);

fileListingTable_registration fileListingTable_user_context;

void            initialize_table_fileListingTable(void);
void            shutdown_table_fileListingTable(void);


/**
 * Initializes the fileListingTable module
 */
void
init_fileListingTable(void)
{
    DEBUGMSGTL(("verbose:fileListingTable:init_fileListingTable",
                "called\n"));

    /*
     * TODO:300:o: Perform fileListingTable one-time module initialization.
     */

    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("fileListingTable"))
        initialize_table_fileListingTable();

}                               /* init_fileListingTable */

/**
 * Shut-down the fileListingTable module (agent is exiting)
 */
void
shutdown_fileListingTable(void)
{
    if (should_init("fileListingTable"))
        shutdown_table_fileListingTable();

}

/**
 * Initialize the table fileListingTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_fileListingTable(void)
{
    fileListingTable_registration *user_context;
    u_long          flags;

    DEBUGMSGTL(("verbose:fileListingTable:initialize_table_fileListingTable", "called\n"));

    /*
     * TODO:301:o: Perform fileListingTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize fileListingTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context =
        netsnmp_create_data_list("fileListingTable", NULL, NULL);

    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;

    /*
     * call interface initialization code
     */
    _fileListingTable_initialize_interface(user_context, flags);
}                               /* initialize_table_fileListingTable */

/**
 * Shutdown the table fileListingTable 
 */
void
shutdown_table_fileListingTable(void)
{
    /*
     * call interface shutdown code
     */
    _fileListingTable_shutdown_interface(&fileListingTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
fileListingTable_rowreq_ctx_init(fileListingTable_rowreq_ctx * rowreq_ctx,
                                 void *user_init_ctx)
{
    UNUSED(user_init_ctx);
    DEBUGMSGTL(("verbose:fileListingTable:fileListingTable_rowreq_ctx_init", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:210:o: |-> Perform extra fileListingTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
}                               /* fileListingTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void
fileListingTable_rowreq_ctx_cleanup(fileListingTable_rowreq_ctx *
                                    rowreq_ctx)
{
    DEBUGMSGTL(("verbose:fileListingTable:fileListingTable_rowreq_ctx_cleanup", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:211:o: |-> Perform extra fileListingTable rowreq cleanup.
     */
}                               /* fileListingTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
fileListingTable_pre_request(fileListingTable_registration * user_context)
{
    UNUSED(user_context);
    DEBUGMSGTL(("verbose:fileListingTable:fileListingTable_pre_request",
                "called\n"));

    /*
     * TODO:510:o: Perform fileListingTable pre-request actions.
     */

    return MFD_SUCCESS;
}                               /* fileListingTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
fileListingTable_post_request(fileListingTable_registration * user_context,
                              int rc)
{
    UNUSED(user_context);
    UNUSED(rc);
    DEBUGMSGTL(("verbose:fileListingTable:fileListingTable_post_request",
                "called\n"));

    /*
     * TODO:511:o: Perform fileListingTable post-request actions.
     */

    return MFD_SUCCESS;
}                               /* fileListingTable_post_request */


/** @{ */
