/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $
 *
 * $Id:$
 */
#ifndef FILELISTINGTABLE_DATA_ACCESS_H
#define FILELISTINGTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     *********************************************************************
     * function declarations
     */

    /*
     *********************************************************************
     * Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table fileListingTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * CE-SNMP-MIB::fileListingTable is subid 6 of media.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.38010.3.4.6, length: 10
     */
#define FILELISTINGTABLE_CACHE_TIMEOUT   60

    int            
        fileListingTable_init_data(fileListingTable_registration *
                                   fileListingTable_reg);


    void            fileListingTable_container_init(netsnmp_container **container_ptr_ptr, netsnmp_cache *cache);
    void            fileListingTable_container_shutdown(netsnmp_container *
                                                        container_ptr);

    int             fileListingTable_container_load(netsnmp_container *
                                                    container);
    void            fileListingTable_container_free(netsnmp_container *
                                                    container);

    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    /*
     *********************************************************************
     * Since we have no idea how you really access your data, we'll go with
     * a worst case example: a flat text file.
     */
#define MAX_LINE_SIZE 256
    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/
    int             fileListingTable_row_prep(fileListingTable_rowreq_ctx *
                                              rowreq_ctx);



#ifdef __cplusplus
}
#endif
#endif                          /* FILELISTINGTABLE_DATA_ACCESS_H */
