#ifndef	_UINPUT_PROCESS_EXIT_CODE_H_
#define	_UINPUT_PROCESS_EXIT_CODE_H_

typedef enum
{
	UIN_PEC_SUCCESS = 0,
	UIN_PEC_OUT_OF_MEMORY = 1,
	UIN_PEC_ERR_FDNO=2,
	UIN_PEC_ERR_ExternalError=3,
	UIN_PEC_ERR_NotAvailable=4,
	UIN_PEC_ERR_InvalidParameter=5,
}UIN_PROCESS_EXIT_CODE, *P_UIN_PROCESS_EXIT_CODE;

#endif	//_UINPUT_PROCESS_EXIT_CODE_H_

