/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.notify.conf 17455 2009-04-05 09:53:29Z magfr $
 */
#ifndef RESTARTINITIATED_H
#define RESTARTINITIATED_H

#ifdef __cplusplus
extern "C" {
#endif

void init_asTrap(void);
void DeinitTrap(void);

#ifdef __cplusplus
}
#endif

#endif                          /* RESTARTINITIATED_H */

