#!/bin/sh

# Sanity checks.
[ -x /sbin/udevd ] || exit 0

start() {
    pid=`ps -fA | grep "udevd" | grep "daemon" | awk '{print $2}'`
    exitCode=$?
    if [ ${exitCode} -eq 0 ]; then
        if [ ! -z "${pid}" ]; then
            echo "udevd Service already exists!"
            exit 1
        fi
    fi
    
    echo "Starting udevd --daemon Service..."
    udevd --daemon
	#coldplug
	udevadm trigger --subsystem-match=input
}	

stop() {
	echo -n "Stopping udevd Service..."
	killall udevd
	ProcessExitCode=$?
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
    stop
    start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac
