######################################################################
# Automatically generated by qmake (2.01a) Mon May 9 18:24:04 2016
######################################################################

TEMPLATE = app
TARGET = Md5-Base64-Permision
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Md5-Base64-Permision.cpp

QT +=core  gui webkit  widgets dbus
